version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/apps/dumbPaintTool"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/tlogg"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/ttkDesigner"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/ttkode"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/libs/pyTermTk"
    schedule:
      interval: "weekly"
