[mypy]
python_version = 3.12
disallow_untyped_defs = True
check_untyped_defs = True
strict_optional = True
mypy_path = libs/pyTermTk
exclude = (?x)(
    .*_test\.py
    | test_.*\.py
  )

[mypy-ruamel.*]
ignore_missing_imports = True

[mypy-pyblock_builder.*]
ignore_missing_imports = True

