"""Type stub for conftest.py fixtures."""

from typing import Callable
import TermTk as ttk

class _FakeCanvas(ttk.TTkCanvas):
    def text_in_line(self, line: int, text: str) -> bool: ...
    def text_in_canvas(self, text:str) -> bool: ...
    def canvas_to_string(self) -> str: ...

def fake_canvas() -> Callable[[int, int], _FakeCanvas]: ...
